### ISSUE TITLE
可以提供 createFetchAction 的用例吗

### ISSUE THREAD

**Issue by liaokaien** [nefe/iron-redux#5]
字面上`createFetchAction` 应该可以返回一个 actionCreator， 但是看代码
``` ts
export function createFetchAction<Key>(
...
 const action = {
      stateKey,
      types,
      meta,
      params,
      url,
      method
    };
```

返回的actionCreator并不能返回带有`type`字段的POJO

**Comment by jasonHzq** [comment]
是的，这个是通用的 middleware 支持的。这里没有指定，而是假定有一个 通用的 redux fetch middleware

**Comment by jasonHzq** [comment]
createFetchAction 和 https://github.com/alibaba/pont 结合很好

**Comment by ryanyu104** [comment]
> 是的，这个是通用的 middleware 支持的。这里没有指定，而是假定有一个 通用的 redux fetch middleware

所以 我用redux-axios-middlewar 也是可以的吧？
